### ISSUE TITLE
The log entries loaded all

### ISSUE THREAD

**Issue by agusmakmun** [agusmakmun/django-log-viewer#1]
> This problem was found when "Log files" was clicked, and go to another page, \
> and log entries loaded all. But after the dropdown "Show entries _(page length)_" the pagination working fine.

**Comment by ks-manish** [comment]
In function fnDisplayEnd
`fnDisplayEnd: function () {
			**_var a = this._iDisplayLength_**,
				b = this._iDisplayStart,
				c = b + a,
				d = this.aiDisplay.length,
				e = this.oFeatures,
				f = e.bPaginate;
			return e.bServerSide ? !1 === f || -1 === a ? b + d : Math.min(b + a, this._iRecordsDisplay) : !f || c > d || -1 === a ? d : c
		}`

var a is being initialized as string somehow...which is causing issue. On changing page length from dropdown this var is getting initialized as number.
on parsing it to Int as  var a = parseInt(this._iDisplayLength) ,it works fine.
