### ISSUE TITLE
LOG FILES need paging and search form

### ISSUE THREAD

**Issue by kwangsooshin** [agusmakmun/django-log-viewer#14]
Hi, I want a new feature.

For example, I usually write logs each day, but I need to store 100 days.

And there are 2~3 Loggers. That means, after 100 days, there are 300 log files in `LOG FILES` area.

So, I think `LOG FILES` need paging and search form. Thank you!

![image](https://user-images.githubusercontent.com/29035439/91926010-3bb27700-ed11-11ea-80ab-e9de0937c61e.png)

**Comment by agusmakmun** [comment]
@kwangsooshin it already solved by @jsoligny
