### ISSUE TITLE
Base url cannot be resolved after upgrading to Django 3.x / authentication

### ISSUE THREAD

**Issue by CountBigBang** [agusmakmun/django-log-viewer#21]
After upgrading to Django 3.2. (from 2.2), the base url `/admin/log_viewer` cannot be resolved. No view is displayed. This may be due to the fact that I overrode the [default admin site](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#overriding-default-admin-site).

However, including the `log_viewer.urls` in my own app works:
`path('myownapp/logs/', include('log_viewer.urls')),`

I edited the original comment and removed my question regarding the permissions since a quick code review showed that the log views are only accessible to superusers. This should be the optimal solution in most scenarios.

**Comment by agusmakmun** [comment]
Hello @CountBigBang, thanks for reporting a bug.
I have resolved this issue into [v1.1.3](https://github.com/agusmakmun/django-log-viewer/releases/tag/v1.1.3)
Please upgrade your log viewer:

```
pip install django-log-viewer --upgrade
```
