### ISSUE TITLE
Package for Version 1.1.3 missing at Pypi

### ISSUE THREAD

**Issue by jwaschkau** [agusmakmun/django-log-viewer#22]
The current version at PyPi is 1.1.2 but at this repository there is already a release for 1.1.3.
See: https://pypi.org/project/django-log-viewer/#history

Is it possible to upload the current version to PyPi?

**Comment by agusmakmun** [comment]
good catch @jwaschkau, that was my mistaken.
I have uploaded a new version, please try again.
