### ISSUE TITLE
Module "log_viewer" not found when installing version 1.1.3 

### ISSUE THREAD

**Issue by CountBigBang** [agusmakmun/django-log-viewer#23]
Some problem with version 1.1.3 prevents the the package from being properly installed. There is no folder "log_viewer" in `site-packages` after installing with `pip install` (tested on different platforms). There are no error messages and `pip list` indicates that the package is installed. But Django fails to start with the following error message:
`ModuleNotFoundError: No module named 'log_viewer'`
The problem does not occur with version 1.1.2

**Comment by agusmakmun** [comment]
Oh sorry, I just realize that `__init__.py` file is removed in previous commit: https://github.com/agusmakmun/django-log-viewer/commit/607b5e48d9dd75d593f1087263aa978940b6cd6b#diff-b8c8578099bbbb54ad7fca1673516b64786b67a77226f9f326f56773196bec82
