### ISSUE TITLE
newline

### ISSUE THREAD

**Issue by zszep** [agusmakmun/django-log-viewer#30]
There's no newline when viewing the logs. Everything is one big line.

**Comment by agusmakmun** [comment]
Hello @zszep for reporting this issue, seems like happen because of "Not Found" exclude. \
meanwhile, I modify that exclude to the settings, but by default is `None`;

```
LOG_VIEWER_EXCLUDE_TEXT_PATTERN = None  # String regex expression to exclude the log from line
```

can you please upgrade your package which following this command:

```
pip install django-log-viewer --upgrade
```

Please tell us what happen after doing upgrade, is it resolved the issue or not.

cc @tulgaab, @ananasn, @radialmed, @ashok-rai, @jamol1741

**Comment by ashok-rai** [comment]
No, It has not **changed** the log entries in the new iterable row as displayed in the **documentation.**
@agusmakmun, Is there any **extra setup** that we are missing to make the log entries in new lines as shown in the [image](https://camo.githubusercontent.com/88aad3eb2be1f5de2434aefed1d5d92900c54b0ebf5b95de7a8a590a730aef3b/68747470733a2f2f692e696d6775722e636f6d2f6b71787a4970582e706e67)

**Comment by agusmakmun** [comment]
@ashok-rai can you show me the screenshot of your logs? or you can paste the plain of logs here, so I can identify.

**Comment by ashok-rai** [comment]
@agusmakmun,

**This is my log file**
<img width="844" alt="Screen Shot 2022-08-29 at 11 51 51 AM" src="https://user-images.githubusercontent.com/16273725/187133775-e075c824-7858-4132-aa5d-d6478572a7bb.png">

### And, this is the log_viewer UI which doesnot show the log entries with each new lines in the log file
<img width="2002" alt="Screen Shot 2022-08-29 at 11 51 44 AM" src="https://user-images.githubusercontent.com/16273725/187133793-b29365b7-4bd9-4f8c-883f-2db5f81c1a4f.png">

**Comment by agusmakmun** [comment]
ok thanks @ashok-rai, seems your logs not using double `[` and `]` to present the log format:
https://github.com/agusmakmun/django-log-viewer/blob/master/log_viewer_demo/log_viewer_demo/logger.py#L17


```
"[%(levelname)s] %(asctime)s %(name)s: %(message)s"

/|\           /|\
```

to remember that we have pattern in settings as well:

```
LOG_VIEWER_PATTERNS = ['[INFO]', '[DEBUG]', '[WARNING]', '[ERROR]', '[CRITICAL]']
```

so, you need to make sure both setup are corrects.

**Comment by ashok-rai** [comment]
Thank you @agusmakmun, this solves the issues.Now, it is working as expected.
