### ISSUE TITLE
Log viewer does not work with Django 3.1

### ISSUE THREAD

**Issue by jkarwisch** [agusmakmun/django-log-viewer#6]
I'm testing with log_viewer_demo and running into an issue with Django 3.1. After setting the demo up and logging into the admin site, it does not list the log files on the web page: /admin/log_viewer. I'm also seeing the following message in the console from the development server: [05/Aug/2020 19:15:38] "GET /admin/log_viewer/json/ HTTP/1.1" 500 110088. When I run the server with Python -Wd, I also see the following message: RemovedInDjango40Warning: TemplateView passing URL kwargs to the context is deprecated. Reference file_name in your template through view.kwargs instead.

When I install Django 3.0.6, the log_viewer_demo works correctly and get this message: [05/Aug/2020 19:28:23] "GET /admin/log_viewer/json/ HTTP/1.1" 200 448

I'm running this on Python 3.6.8.

**Comment by agusmakmun** [comment]
@jkarwisch thank for reporting this issue, now it supported in newest version `v1.0.7`, please upgrate it.

```
pip install django-log-viewer --upgrade
```
